### ISSUE TITLE
Visualization of reconstruction of wiring diagrams

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/Beeline#19]
Color edges by the number of methods that recovered them. Post to GraphSpace. 
Use as many edges from the ranked list in the reconstruction as are in the original wiring diagram.

**Comment by tmmurali** [comment]
@adbharadwaj What is the status? I know we did not use the visualisations in our manucript. Is there are code for this step? If not, we can close this issue. Otherwise, we can consider if it is useful to integrate the code into BEELINE.

**Comment by adbharadwaj** [comment]
Unfortunately, we do not have any code for this step.
