### ISSUE TITLE
Add updated documentation

### ISSUE THREAD

**Issue by adyprat** [Murali-group/Beeline#23]
Add updated documentation for using BEELINE.

**Comment by adbharadwaj** [comment]
Few things that are missing from the documentation are:

- Python version support (3.6)
- User needs to install requirements before running eval.py
- Is there a need for virtualenv? maybe!

**Comment by tmmurali** [comment]
@amoghpj I think the docs are complete. Can we close this issue?

**Comment by jlaw9** [comment]
Steps to install the required packages is still missing from the documentation

**Comment by adyprat** [comment]
I now added the installation steps to initialize.sh. I'm assuming @jlaw9 was referring to PRROC package.
