### ISSUE TITLE
bioRxiv Figure 3

### ISSUE THREAD

**Issue by rcannood** [Murali-group/Beeline#30]
I quite liked Figure 3 from the bioRxiv paper:

![Screenshot from 2019-08-09 12-34-10](https://user-images.githubusercontent.com/553642/62773267-056cde80-baa2-11e9-8eec-86b231838165.png)

I had a few remarks / questions:

* The different plotting styles (pie / circle / square / progressbar) adds no value to the visualization. To me, it seems like the figure would be easier to interpret if the AUROC, AUPRC and Jaccard Index would use the same shape (as was the case in [our figures](https://raw.githubusercontent.com/dynverse/dynbenchmark_results/1ac55e6c54a950890208b1f7730092d39783dfd2/08-summary/results_suppfig.png) as well).
* I'm missing a summary of the results. According to this Figure, which methods perform well in what areas? This is discussed in the Discussion, but it's not apparent for me in this figure.

**Comment by tmmurali** [comment]
Hi Robert,
  Thanks for your interest in the BEELINE manuscript! We have enjoyed reading the Dynverse paper and been inspired by it.

-  You are right about the shapes. We are moving to uniform shapes in our figures. 

- We are also preparing a summary of the results that highlights the areas in which different methods are strong.

**Comment by tmmurali** [comment]
Figure 6 in the [BEELINE paper in Nature Methods](https://rdcu.be/b1b3H) addresses this issue.
