### ISSUE TITLE
An issue of Beeline/Algorithms/SCRIBE/runScribe.R

### ISSUE THREAD

**Issue by AprilYuge** [Murali-group/Beeline#39]
Line 122: ordering_genes not defined.

**Comment by adyprat** [comment]
Could you please provide more information on how you got this error?

**Comment by AprilYuge** [comment]
When I ran "Rscript runScribe.R -e ./data/SCRIBE_copd_count.csv -c ./data/copd_pseudotime.csv -g ./data/SCRIBE_GeneData.csv -o ./output/SCRIBE -d 5 -l 0 -m ucRDI -x negbinomial.size --outFile copd_out.csv -i", I got an error saying object 'ordering_genes' not found. I looked through runScribe.R and I think the reason is that 'ordering_genes' is not defined before line 122. I checked the documentation of monocle and added "ordering_genes <- disp_table$gene_id" to make it finally work.

**Comment by adyprat** [comment]
Ah, I must have missed that. Thanks!

**Comment by AprilYuge** [comment]
No problem!
