### ISSUE TITLE
GRN ground-truth datasets

### ISSUE THREAD

**Issue by amoghpj** [Murali-group/Beeline#4]

**Comment by tmmurali** [comment]
@jlaw9 Can you summarise the three types of ground truth networks we use and close this comment?

**Comment by jlaw9** [comment]
We use three types of human and mouse ground truth networks.
 
1. Non-specific ChIP-seq datasets from RegNetwork, TRRUST, and DoRothEA
2. Cell-type specific ChIP-seq and loss and gain of function datasets from ChEA, ChIP-Atlas and ESCAPE
3. Functional association networks from STRING

Below is the table we included in the paper:

| Sp    | Source                         | #TFs  | #Genes | #Edges    | Density | Gene expression dataset |
|-------|--------------------------------|-------|--------|-----------|---------|-------------------------|
| Mouse | HSC, E, L, G-M ChIP-Atlas      | 137   | 19,324 | 1,078,888 | 0.407   | mHSC, Nestorowa et al.  |
| Mouse | DC, ChIP-Atlas                 | 36    | 11,092 | 30,658    | 0.077   | mDC, Shalek et al.      |
| Mouse | mESC, ESCAPE+ ChIP-Atlas       | 247   | 25,703 | 6,348,394 | 0.154   | mESC, Hayashi et al.    |
| Mouse | mESC, LOGOF, ESCAPE            | 57    | 18,427 | 104,797   | 0.1     | mESC, Hayashi et al.    |
| Mouse | TRRUST + RegNetwork            | 1,455 | 17,852 | 100,139   | 0.004   |                         |
| Mouse | STRING                         | 1,350 | 7,771  | 157,134   | 0.015   |                         |
| Human | hESC, ChEA + ChIP-Atlas        | 130   | 18,104 | 436,563   | 0.186   | Chu et al.              |
| Human | HEPG2, ChEA + ChIP-Atlas       | 84    | 16,822 | 342,862   | 0.243   | Camp et al.             |
| Human | TRRUST + RegNetwork + DoRothEA | 2,165 | 23,566 | 386,293   | 0.008   |                         |
| Human | STRING                         | 1,489 | 8,806  | 198,285   | 0.015   |                         |
