### ISSUE TITLE
Lacking of "Type" in ground truth network 

### ISSUE THREAD

**Issue by Hsu-Che-Wei** [Murali-group/Beeline#43]
Hi Aditya,

I would like to ask what if the ground truth network I have does not have "+" (activation) or "-" (repression). Is it still possible to run evaluation process? I only know that there exist regulation relationship between Gene1 and Gene2, but are not sure about the gene pairs interaction type.

Thank you.

Best,
Che-Wei

**Comment by adyprat** [comment]
Hi,
You should be able to use evaluation script without the Type column; most should work except for signed early precision computation. Let me know if you have any difficulty.
Best,
Aditya

**Comment by Hsu-Che-Wei** [comment]
Hi Aditya,

When I want to use BLEvaluator.py to estimate AUROC and AUPRC, I found that although there is output files, rankedEdges.csv is missing. Could that because that I didn't finish running the script? I stopped the script when it is running SCRIBE cause it's taking too long (more than 3 days). If that is the case, could you please tell me how can I generate rankedEdges.csv for the rest of the algorithms?

Thank you

Best,
Che-Wei

**Comment by adyprat** [comment]
You're right. If you abort an algorithm, it does not create a rankedEdges.csv file. In order to avoid running an algorithm, you can set "should_run: [False]" in the config.yaml file. Hope that helps.
