### ISSUE TITLE
Data availability from paper

### ISSUE THREAD

**Issue by calebclayreagor** [Murali-group/Beeline#49]
Hello again, I was wondering if you've posted the ground truth networks for the experimental single-cell RNA-seq datasets from the paper anywhere. Thanks for your help!

**Comment by ktakers** [comment]
Please find the ground truth networks for experimental scRNA-seq data sets in BEELINE-Networks.zip available at https://zenodo.org/record/3701939#.YDZ_PuhKiUk .
