### ISSUE TITLE
Experimental single cell expression datasets

### ISSUE THREAD

**Issue by amoghpj** [Murali-group/Beeline#5]
- [x] THP1
  - Currently uses the expression of only the 45 TFs in the evaluation network. What if we used the expression of all genes?
- [x] mESC (SCODE)
- [x] hESC (SCODE)
- [ ] mES-PE (SCODE)
- [ ] zHSC (GRNVBEM)
   - Differential expression
- [ ] mES-retinoic (SCINGE)
- [ ] mRetina (GRNBoost2, GENIE3)
- [ ] mHSC (SCRIBE)
  - No processed files available
- [ ] mDC LEAP
  - No processed files available

**Comment by tmmurali** [comment]
I am closing since we have completed the analysis. I am not documenting in this issue which datasets we used. People can read our paper to get the information.
