### ISSUE TITLE
Running without trueEdges (refNetwork.csv)

### ISSUE THREAD

**Issue by doncarlos999** [Murali-group/Beeline#53]
Hi, 

Thanks for this great tool.

In your documentation is says that it is possible to run base pipeline without a refNetwork.csv file. However when I try to run:
`python BLRunner.py --config config-files/config_d0.yaml`

I get the following error:
```
Traceback (most recent call last):
  File "BLRunner.py", line 77, in <module>
    main()
  File "BLRunner.py", line 59, in main
    evaluation = br.ConfigParser.parse(conf)
  File "/scratch/projects/GRN/Beeline/BLRun/__init__.py", line 137, in parse
    config_map['output_settings']))
  File "/scratch/projects/GRN/Beeline/BLRun/__init__.py", line 67, in __init__
    self.runners: Dict[int, Runner] = self.__create_runners()
  File "/scratch/projects/GRN/Beeline/BLRun/__init__.py", line 88, in __create_runners
    data['trueEdges'] = dataset['trueEdges']
KeyError: 'trueEdges'
```

Any help with this would be greatly appreciated.

Thanks

**Comment by adyprat** [comment]
Hi @doncarlos999 ,
Apologies for the confusion. You can indeed infer GRNs without needing a rankedEdges.csv file. However, it looks like BLRunner object is initalized with it anyway. While I work on a fix, there are a couple of options:

1) You can create an empty csv file and include it in the config file. 
2) Another option is to comment out [line #88 here ]( https://github.com/Murali-group/Beeline/blob/02961beeb48af308059aa10390ecb68ce5c8bb59/BLRun/__init__.py#L88) (which is what I was going to do to fix this issue).

Let me know if that works.

Thanks,

Aditya

**Comment by doncarlos999** [comment]
Great, option 1 fixed the problem for me.

Thanks for the rapid response!
