### ISSUE TITLE
How to compute the variance of genes using 'gam'.

### ISSUE THREAD

**Issue by mahp-scut** [Murali-group/Beeline#58]
Hi,
Thank you very much for this tool. I am preprocessing other scRNA-seq dataset following the procedure mentioned in your paper, that is, "We used the general additive model implemented in the ‘gam’ R package to compute the variance and the P value of this variance". However, i don't know how to compute the variance of genes using the ‘gam’ R package. It will be great if you can provide some example codes!
Thanks!

**Comment by adyprat** [comment]
The R notebooks for pre-processing experimental scRNA-seq datasets are now under https://github.com/Murali-group/Beeline/tree/master/inputs/scRNAseq_preprocessing. The data sources (for input files) are listed in the notebooks.

**Comment by mahp-scut** [comment]
Thank you very much for your response!
