### ISSUE TITLE
where is the tfs+500 and tfs+1000 datasets?

### ISSUE THREAD

**Issue by pengrui-code** [Murali-group/Beeline#98]
Hello, I am very grateful for your outstanding work, but I could not find the 'tfs+500' and 'tfs+1000' datasets from the paper on the provided data website. How can I access them?

**Comment by yiqisu** [comment]
Hi, thanks for your question. Please refer to [generateExpInputs.py](https://github.com/Murali-group/Beeline/blob/b99be2ff94654ef5b0751a9db70b4c6b9e1e0778/generateExpInputs.py) for an example of generating datasets with all TFs and 500 genes (TFs+500). You can generate TFs+1000 datasets by adjusting the '-n' or '--numGenes' parameter to 1000.

**Comment by pengrui-code** [comment]
> Hi, thanks for your question. Please refer to [generateExpInputs.py](https://github.com/Murali-group/Beeline/blob/b99be2ff94654ef5b0751a9db70b4c6b9e1e0778/generateExpInputs.py) for an example of generating datasets with all TFs and 500 genes (TFs+500). You can generate TFs+1000 datasets by adjusting the '-n' or '--numGenes' parameter to 1000.

Thanks for your answer, I'll give it a try.
